### ISSUE TITLE
create website for the package

### ISSUE THREAD

**Issue by jialul** [MichaelLLi/evalITR#13]

**Comment by xiaolong-y** [comment]
~~Done here: https://github.com/MichaelLLi/evalITR/pull/5~~

**Comment by xiaolong-y** [comment]
To-do:
- dissect the current documentation into smaller pieces 
- shorter welcome page (home)
- add a vignette with double machine learning as example
- prepare for JSS

**Comment by jialul** [comment]
Documentations and websites are now in [https://michaellli.github.io/evalITR/](https://michaellli.github.io/evalITR/)
