### ISSUE TITLE
add infrastructure for training under sample splitting

### ISSUE THREAD

**Issue by xiaolong-y** [MichaelLLi/evalITR#20]
- [x] `itr_single_outcome`
- [x] `compute_qoi`
- [x] clean up and documentation 
- [x] `summary()`
- [x] fix plotting bug
- [x] use ratio argument to indicate sample splitting
- [x] reformat ifelse conditions 
- [x] add haven in the name space (but a spurious note)
- [x] `run_itr`: default value of `n_folds = 5`, and `ratio = 0` so users only specify `n_folds` for `cv`, and ratio for sample splitting (for cv, need to ensure either `ratio` is `unspecifed`, or `= 0`. Otherwise `ratio` takes precedence over `n_folds`)

**Comment by jialul** [comment]
Closing this issue since it has been done in the latest `causal-ml` branch.

**Comment by jialul** [comment]
Fixed this issue with commit [a9280ea](https://github.com/MichaelLLi/evalITR/commit/a9280ea2d4742cdd340bcccef8b9abe1ab5964f5)

**Comment by jialul** [comment]
Fixed this issue with commit [a9280ea](https://github.com/MichaelLLi/evalITR/commit/a9280ea2d4742cdd340bcccef8b9abe1ab5964f5)
