### ISSUE TITLE
separate training/testing with compute qoi

### ISSUE THREAD

**Issue by xiaolong-y** [MichaelLLi/evalITR#26]
- [x] seperate train under sample splitting and estimate into two functions 
- [x] seperate train under cross fitting and estimate into two functions 
- [x] ensure the master function of run_estimate also exists as an option

**Comment by jialul** [comment]
Fixed this issue with the commit [a9280ea](https://github.com/MichaelLLi/evalITR/commit/a9280ea2d4742cdd340bcccef8b9abe1ab5964f5).
