### ISSUE TITLE
allow users to estimate the ITRs with their own models

### ISSUE THREAD

**Issue by xiaolong-y** [MichaelLLi/evalITR#27]
No problem setting quantities of interest directly from `run` function now but quantities are only returned as a list of unnamed elements.

**Comment by xiaolong-y** [comment]
Naming the elements in the output 
- in `output$qoi`: each outcome list has outcome variable name

**Comment by jialul** [comment]
- [x] Next step: allow users to estimate the ITRs using their own models + their own evaluation metrics

**Comment by jialul** [comment]
Incorporated `caret` package functions, which allow users to design their own models

**Comment by jialul** [comment]
Finished this task in [commit 4cd36a7](4cd36a78e3a7c83b39b28c349b761b281d3b9007)
