### ISSUE TITLE
Minor error in PAVcv and PAPEcv

### ISSUE THREAD

**Issue by Rikkkkkin** [MichaelLLi/evalITR#40]
Hi,

If we specify centered=FALSE option in PAVcv and PAPEcv, it returns the same values when setting centered=TRUE. This seems because the option is not reflected in the PAV (or PAPE) function in the for () loop: e.g. line 68 in PAVcv.

For applied researcher, centered=FALSE may provide more relevant information. Additionally I wonder if the default output can be the estimate output with centered=FALSE option **plus** mean(Y), with same SD, if such a computation allows.

**Comment by MichaelLLi** [comment]
Thank you for reaching out - thank you for noting the error! Let us investigate if it is possible to show both centered and uncentered through the output (if I understood your point correctly). Could you provide a bit more color on why centered=FALSE would be more relevant? The population level quantity is unaffected by the shift.

**Comment by Rikkkkkin** [comment]
* { font-size: 13px; font-family: 'MS Pゴシック', sans-serif;}p, ul, ol, blockquote { margin: 0;}a { color: #0064c8; text-decoration: none;}a:hover { color: #0057af; text-decoration: underline;}a:active { color: #004c98;}
Thanks for your reply!

Answering your question, we want to know how much is improved with the ITR – for example, suppose that a weight reduction (outcome) by a drug (intervention) is 3kg on average, and 0kg in control. PAV without centering may be 5kg, then we can compare with 3kg and discuss how much does the ITR work. We can conclude that 2kg additional weight reduction is significant. PAV with centering may be 3.5kg, and what to compare this value is not straightforward.




Rik




----- Original Message -----




From: "Michael Lingzhi Li" ***@***.***>

To: "MichaelLLi/evalITR" ***@***.***>

Cc: "Rikkkkkin" ***@***.***>; "Author" ***@***.***>

Date: 2023/06/09 金 09:33

Subject: Re: [MichaelLLi/evalITR] Minor error in PAVcv and PAPEcv (Issue #40)







Thank you for reaching out - thank you for noting the error! Let us investigate if it is possible to show both centered and uncentered through the output (if I understood your point correctly). Could you provide a bit more color on why centered=FALSE would be more relevant? The population level quantity is unaffected by the shift.

**Comment by MichaelLLi** [comment]
Hi Rik:

Thank you for your comment. Well understood.

We are working on a significant revamp and upgrade of the package that would be released soon. We will incorporate the error you pointed out. Thank you so much!

Best
-M
