### ISSUE TITLE
add GATE to the qoi

### ISSUE THREAD

**Issue by jialul** [MichaelLLi/evalITR#9]
Adding GATE to `itr_qoi.R` as a quantity of interests to enable estimation of GATE after training various machine learning models of user's choice.

To do:   
- [x] : fix bug of GATEcv with `bartMachine`
- [x] : estimate GATEcv in `itr_run`
- [x] : estimating GATE in `itr_run`
- [x] : add algorithm indicator to the fitted result 
- [x] : summary statistics in `itr_summary`
- [x] : enable users to set `ngates` directly in `run`

Possible next steps:
- [x] : standardize algorithm names between bart and bartMachine (`main` and function names)
- [x] : standalone `run` function to train and estimate GATE that is separate from `itr_run`
- [x] : separate summary function

**Comment by xiaolong-y** [comment]
https://github.com/MichaelLLi/evalITR/pull/19

**Comment by xiaolong-y** [comment]
Adding GATE to `itr_qoi.R` as a quantity of interests to enable estimation of GATE after training various machine learning models of user's choice.

To do:   
- [ ] : estimating GATEcv with `bartMachine`
- [ ] : estimating GATE
- [x] : add algorithm indicator to the fitted result 
- [x] : summary statistics in `itr_summary`

Possible next steps:
- [ ] : standardize algorithm names between bart and bartMachine (`main` and function names)
- [ ] : standalone `run` function to train and estimate GATE that is separate from `itr_run`
- [ ] : enable users to set `ngates` directly in `run`
- [ ] : separate summary function

**Comment by jialul** [comment]
Fixed the summary function for GATE with commit [a9280ea](https://github.com/MichaelLLi/evalITR/commit/a9280ea2d4742cdd340bcccef8b9abe1ab5964f5) and use `bartCause` instead of `bartMachine` consistently.
